# Generated by Django 3.1 on 2021-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(default='', verbose_name='Приватный ключ')),
                ('public_key', models.TextField(default='', verbose_name='Публичный ключ')),
            ],
            options={
                'verbose_name': 'Конфигурация сайта',
            },
        ),
    ]
