# Generated by Django 3.1 on 2021-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='limit_to_retry',
            field=models.IntegerField(default=5, verbose_name='Количество попыток запросов интеграций'),
        ),
    ]
