# Generated by Django 3.1 on 2021-09-09 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garpix_page", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLogsPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garpix_page.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Страница "Журнал изменений (список)"',
                "verbose_name_plural": 'Страницы "Журнал изменений (список)"',
            },
            bases=("garpix_page.basepage",),
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("changed", models.DateTimeField(auto_now=True, verbose_name="Дата/время изменения")),
                ("role", models.CharField(blank=True, max_length=128, verbose_name="Роль пользователя")),
                (
                    "action_on_model",
                    models.CharField(
                        choices=[
                            ("create", "Заявка создана"),
                            ("update", "Заявка обновлена"),
                            ("delete", "Заявка удалена"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, verbose_name="Наименование")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал изменений",
                "verbose_name_plural": "Журналы изменений",
                "ordering": ("changed",),
            },
        ),
    ]
