# Generated by Django 3.1 on 2021-09-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='field',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Поле'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='newvalue',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Текущее значение'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='oldvalue',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Предыдущее значение'),
        ),
    ]
