# Generated by Django 3.1 on 2021-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0004_auto_20211013_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='newvalue',
            field=models.TextField(blank=True, default='', verbose_name='Текущее значение'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='oldvalue',
            field=models.TextField(blank=True, default='', verbose_name='Предыдущее значение'),
        ),
    ]
