# Generated by Django 3.1 on 2021-07-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handbookblacklistpage',
            options={'verbose_name': 'Страница "Справочник (черный список)"', 'verbose_name_plural': 'Страницы "Справочники (черный список)"'},
        ),
        migrations.AlterModelOptions(
            name='handbookpage',
            options={'verbose_name': 'Страница "Справочник"', 'verbose_name_plural': 'Страницы "Справочники"'},
        ),
    ]
