# Generated by Django 3.1 on 2021-07-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_auto_20210708_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Стоп-фактор',
                'verbose_name_plural': 'Стоп-факторы',
            },
        ),
        migrations.CreateModel(
            name='WarningSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Предупредительный сигнал',
                'verbose_name_plural': 'Предупредительные сигналы',
            },
        ),
    ]
