# Generated by Django 3.1 on 2021-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_stopfactor_warningsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('bank_reason', models.TextField(verbose_name='Причина банка')),
            ],
            options={
                'verbose_name': 'Элемент ЧС',
                'verbose_name_plural': 'Черный список',
            },
        ),
    ]
