# Generated by Django 3.1 on 2021-07-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_blacklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopfactor',
            name='stop_factor_exception',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Исключения'),
        ),
    ]
