# Generated by Django 3.1 on 2021-07-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0002_auto_20210705_1805'),
        ('garpix_page', '0001_initial'),
        ('handbook', '0005_stopfactor_stop_factor_exception'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookStopFactorsPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Справочник (стоп-факторы)"',
                'verbose_name_plural': 'Страницы "Справочники (стоп-факторы)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='HandbookWarningSignalsPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Справочник (предупреждающие сигналы)"',
                'verbose_name_plural': 'Страницы "Справочники (предупреждающие сигналы)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.DeleteModel(
            name='HandbookPage',
        ),
    ]
