# Generated by Django 3.1 on 2021-10-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0007_auto_20210908_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistitem',
            name='bank_reason',
        ),
        migrations.AddField(
            model_name='blacklistitem',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='blacklistitem',
            name='inn',
            field=models.CharField(default='', max_length=12, verbose_name='Инн'),
        ),
        migrations.AlterField(
            model_name='blacklistitem',
            name='title',
            field=models.CharField(blank=True, max_length=256, verbose_name='Название'),
        ),
    ]
