# Generated by Django 3.1 on 2021-10-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0008_auto_20211018_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistitem',
            name='inn',
            field=models.CharField(max_length=12, unique=True, verbose_name='Инн'),
        ),
    ]
