# Generated by Django 3.1 on 2021-07-09 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalBindingsPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Карточка принципала (связи)"',
                'verbose_name_plural': 'Страницы "Карточка принципала (связи)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='PrincipalCommonInfoPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Карточка принципала (общая информация)"',
                'verbose_name_plural': 'Страницы "Карточка принципала (общая информация)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='PrincipalCoownersPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Карточка принципала (совладельцы)"',
                'verbose_name_plural': 'Страницы "Карточка принципала (совладельцы)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='PrincipalDocumentsPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Карточка принципала (документы)"',
                'verbose_name_plural': 'Страницы "Карточка принципала (документы)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='PrincipalFinancialReportPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Карточка принципала (финансовая отчетность)"',
                'verbose_name_plural': 'Страницы "Карточка принципала (финансовая отчетность)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='PrincipalLimitPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Карточка принципала (лимит)"',
                'verbose_name_plural': 'Страницы "Карточка принципала (лимит)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='PrincipalPortfolioPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Карточка принципала (портфолио)"',
                'verbose_name_plural': 'Страницы "Карточка принципала (портфолио)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='PrincipalRatePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Карточка принципала (рейтинг)"',
                'verbose_name_plural': 'Страницы "Карточка принципала (рейтинг)"',
            },
            bases=('garpix_page.basepage',),
        ),
    ]
