# Generated by Django 3.1 on 2021-07-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('inn', models.CharField(max_length=32, verbose_name='ИНН')),
                ('region', models.CharField(max_length=64, verbose_name='Регион')),
                ('okved', models.CharField(max_length=1024, verbose_name='ОКВЭД (Основные)')),
            ],
            options={
                'verbose_name': 'Бенефициар',
                'verbose_name_plural': 'Бенефициар',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('inn', models.CharField(max_length=32, verbose_name='ИНН')),
                ('region', models.CharField(max_length=64, verbose_name='Регион')),
                ('okved', models.CharField(max_length=1024, verbose_name='ОКВЭД (Основные)')),
            ],
            options={
                'verbose_name': 'Принципал',
                'verbose_name_plural': 'Принципалы',
            },
        ),
    ]
