# Generated by Django 3.1 on 2021-08-09 13:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20210804_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Лимит принципала'),
        ),
    ]
