# Generated by Django 3.1 on 2021-08-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_principal_accounting_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='accounting_forms',
        ),
    ]
