# Generated by Django 3.1 on 2021-08-19 13:58

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0008_remove_principal_accounting_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Название')),
                ('document', models.FileField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Документ юр. лицо')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_document', to='entity.principal', verbose_name='Принципал')),
            ],
            options={
                'verbose_name': 'Документ юр. лица',
                'verbose_name_plural': 'Документы юр. лица',
            },
        ),
    ]
