# Generated by Django 3.1 on 2021-08-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ Принципала', 'verbose_name_plural': 'Документы Принципала'},
        ),
    ]
