# Generated by Django 3.1 on 2021-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_auto_20210819_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='principal',
            name='birth_place',
            field=models.CharField(blank=True, max_length=300, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='principal',
            name='citizenship',
            field=models.CharField(blank=True, max_length=400, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='principal',
            name='collect_by_whom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='principal',
            name='collect_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='principal',
            name='department_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='principal',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='principal',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='principal',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='principal',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='principal',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='principal',
            name='registration_address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Адрес регистрации'),
        ),
    ]
