# Generated by Django 3.1 on 2021-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0012_auto_20210819_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='registration_address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
