# Generated by Django 3.1 on 2021-09-08 13:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0017_auto_20210907_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='document',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='document',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='principal',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='principal',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_auditor', to='entity.person', verbose_name='Аудитор'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='auditor_opinion',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Мнение аудитора'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='eio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_eio', to='entity.person', verbose_name='Единоличный исполнительный орган'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='evarage_number_of_employees',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Среднесписочная численность'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='fl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_fl', to='entity.person', verbose_name='Физическое лицо'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='lpr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_lpr', to='entity.person', verbose_name='Лицо, принимающее решения'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='lpr_post',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Должность ЛПР'),
        ),
    ]
