# Generated by Django 3.1 on 2021-09-28 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0020_auto_20210917_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='statutory_document',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='attorney_document',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Доверенность'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='no_audit',
            field=models.BooleanField(null=True, verbose_name='Аудит не проводится'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='regulation_document',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Устав'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ ]*$', 'Специальные символы не допускаются, за исключением "-"'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(22)], verbose_name='Фамилия'),
        ),
    ]
