# Generated by Django 3.1 on 2021-09-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0021_auto_20210928_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='no_audit',
            field=models.BooleanField(default=False, verbose_name='Аудит не проводится'),
        ),
    ]
