# Generated by Django 3.1 on 2021-09-28 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0022_auto_20210928_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='evarage_number_of_employees',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='average_number_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Среднесписочная численность'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_correspondent_account_cb',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(20)], verbose_name='Корреспондентский счет в ЦБ'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(20)], verbose_name='Банковский счет'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='okved',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^([\\s\\.]?[0-9]+)+$'), django.core.validators.MaxLengthValidator(8)], verbose_name='ОКВЭД (Основные)'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='title',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$')], verbose_name='Название'),
        ),
    ]
