# Generated by Django 3.1 on 2021-10-06 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0025_auto_20210930_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='other_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Другое Название'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='title',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s. -0-9ivxcdlIVXCDL:]+$', 'Значение должно содержать только кириллицу, цифры, римские цифры')], verbose_name='Название'),
        ),
    ]
