# Generated by Django 3.1 on 2021-10-23 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0026_auto_20211006_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='kpp',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(9, 'Min value should consist of at least 9 characters'), django.core.validators.MaxLengthValidator(9, 'Max value must not contain more than 9 characters')], verbose_name='КПП'),
        ),
    ]
