# Generated by Django 3.1 on 2021-07-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_underwriterspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='underwriterspage',
            options={'verbose_name': 'Страница "Андеррайтеры (список)"', 'verbose_name_plural': 'Страницы "Андеррайтеры (список)"'},
        ),
    ]
