# Generated by Django 3.1 on 2021-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Код смены почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Код сброса пароля'),
        ),
    ]
