# Generated by Django 3.1 on 2021-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210806_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Неудачных попыток'),
        ),
    ]
