# Generated by Django 3.1 on 2021-08-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_key',
            new_name='password_reset_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_change_key',
        ),
    ]
