# Generated by Django 3.1 on 2021-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_changepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_link',
            field=models.CharField(blank=True, default='', max_length=216, verbose_name='Ссылка для сброса пароля'),
        ),
    ]
