# Generated by Django 3.1 on 2021-08-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210831_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('underwriter', 'Андеррайтер'), ('master_underwriter', 'Мастер-андеррайтер'), ('principal', 'Принципал'), ('agent', 'Агент'), ('bank', 'Банк')], default='underwriter', max_length=32, verbose_name='Роль'),
        ),
    ]
