# Generated by Django 3.1 on 2021-08-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210831_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_link',
            new_name='password_reset_key',
        ),
    ]
