# Generated by Django 3.1 on 2021-09-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210831_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Андеррайтер', 'Андеррайтер'), ('Мастер-андеррайтер', 'Мастер-андеррайтер'), ('Принципал', 'Принципал'), ('Агент', 'Агент'), ('Банк', 'Банк')], default='underwriter', max_length=100, verbose_name='Роль'),
        ),
    ]
