# Generated by Django 3.1 on 2021-09-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210908_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Андеррайтер', 'Андеррайтер'), ('Мастер-андеррайтер', 'Мастер-андеррайтер'), ('Принципал', 'Принципал'), ('Агент', 'Агент'), ('Банк', 'Банк')], default='Андеррайтер', max_length=100, verbose_name='Роль'),
        ),
    ]
