# Generated by Django 3.1 on 2021-10-15 10:53

from django.db import migrations, models
import garpix_notify.utils.file


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20211012_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.FileField(blank=True, default='', null=True, upload_to=garpix_notify.utils.file.get_file_path, verbose_name='Лого'),
        ),
    ]
