# Generated by Django 3.1 on 2021-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authority',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=32, null=True, verbose_name='Полномочия'),
        ),
    ]
