# Generated by Django 3.1 on 2021-07-07 14:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import garpix_page.utils.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Название')),
                ('logo', models.FileField(blank=True, default='', upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='BankDocumentsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=256, verbose_name='Группа документов')),
            ],
            options={
                'verbose_name': 'Группа документов банка',
                'verbose_name_plural': 'Группы документов банка',
            },
        ),
        migrations.CreateModel(
            name='BankTariffMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_tariff_matrix', to='bank.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Матрица тарифов банка',
                'verbose_name_plural': 'Матрицы тарифов банка',
            },
        ),
        migrations.CreateModel(
            name='BankLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Установленный лимит')),
                ('current_guaranties_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Действующие БГ')),
                ('orders_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Заявки')),
                ('free_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Свободный остаток')),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_limits', to='bank.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Лимиты банка',
                'verbose_name_plural': 'Лимиты банков',
            },
        ),
        migrations.CreateModel(
            name='BankDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(default='', upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='Документ')),
                ('document_title', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Название документа')),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bank_documents', to='bank.bank', verbose_name='Банк')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_documents', to='bank.bankdocumentsgroup', verbose_name='Группа документов')),
            ],
            options={
                'verbose_name': 'Документ банка',
                'verbose_name_plural': 'Документы банка',
            },
        ),
    ]
