# Generated by Django 3.1 on 2021-07-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bank_bankdocument_bankdocumentsgroup_banklimits_banktariffmatrix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdocumentspage',
            options={'verbose_name': 'Страница "Карточка банка (документы)"', 'verbose_name_plural': 'Страницы "Карточка банка (документы)"'},
        ),
        migrations.AlterModelOptions(
            name='banklimitpage',
            options={'verbose_name': 'Страница "Карточка банка (лимит)"', 'verbose_name_plural': 'Страницы "Карточка банка (лимит)"'},
        ),
        migrations.AlterModelOptions(
            name='bankspage',
            options={'verbose_name': 'Страница "Банки (список)"', 'verbose_name_plural': 'Страницы "Банки (список)"'},
        ),
        migrations.AlterModelOptions(
            name='banktariffspage',
            options={'verbose_name': 'Страница "Карточка банка (тарифы)"', 'verbose_name_plural': 'Страницы "Карточка банка (тарифы)"'},
        ),
    ]
