# Generated by Django 3.1 on 2021-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210708_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdocument',
            name='group',
        ),
        migrations.AddField(
            model_name='bankdocument',
            name='document_type',
            field=models.CharField(choices=[('osn', 'Основная система налогообложения (ОСН)'), ('usn', 'Упрощенная система налогообложения (УСН)'), ('psn', 'Патентная система налогообложения (ПСН)'), ('envd', 'Единый налог на временный доход (ЕНВД)'), ('other', 'Другие документы')], default='other', max_length=64, verbose_name='Тип документа'),
        ),
        migrations.DeleteModel(
            name='BankDocumentsGroup',
        ),
    ]
