# Generated by Django 3.1 on 2021-08-20 13:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20210819_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankGuarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=128, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('maintain_a_guarantee', models.TextField(default='', max_length=500, verbose_name='Обязательства по гарантии')),
                ('sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма гарантии')),
                ('disclosure_conditions', models.TextField(default='', max_length=500, verbose_name='Условия раскрытия БГ')),
                ('rights_and_liabilities_of_the_parties', models.TextField(default='', max_length=500, verbose_name='Права и обязанности сторон')),
                ('termination_of_liabilities', models.TextField(default='', max_length=500, verbose_name='Прекращение обязательств')),
            ],
            options={
                'verbose_name': 'Банковская гарантия',
                'verbose_name_plural': 'Банковские гарантии',
            },
        ),
        migrations.CreateModel(
            name='BankСontract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_protocol_name', models.CharField(default='', max_length=500, verbose_name='Наименование протокола итогов')),
                ('summary_protocol_number', models.CharField(default='', max_length=128, verbose_name='Номер протокола итогов')),
                ('summary_protocol_date', models.DateField(blank=True, null=True, verbose_name='Дата протокола итогов')),
                ('subject_of_contract', models.TextField(default='', max_length=500, verbose_name='Предмет контракта')),
            ],
            options={
                'verbose_name': 'Контракт банка',
                'verbose_name_plural': 'Контракты банка',
            },
        ),
    ]
