# Generated by Django 3.1 on 2021-08-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20210826_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankguarantee',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bank_guarantee', to='bank.bank', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='bankguaranteestatus',
            name='limit_include',
            field=models.BooleanField(default=False, verbose_name='Учитывать при расчете лимита'),
        ),
        migrations.AddField(
            model_name='bankсontract',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bank_contract', to='bank.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='banklimits',
            name='bank',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_limits', to='bank.bank', verbose_name='Банк'),
        ),
    ]
