# Generated by Django 3.1 on 2021-08-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20210826_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankguarantee',
            name='disclosure_conditions',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='Условия раскрытия БГ'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='maintain_a_guarantee',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='Обязательства по гарантии'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='rights_and_liabilities_of_the_parties',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='Права и обязанности сторон'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='termination_of_liabilities',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='Прекращение обязательств'),
        ),
    ]
