# Generated by Django 3.1 on 2021-08-31 08:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20210828_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banklimits',
            options={'verbose_name': 'Лимит банка', 'verbose_name_plural': 'Лимиты банков'},
        ),
        migrations.AlterField(
            model_name='banklimits',
            name='orders_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Общая сумма заявок'),
        ),
    ]
