# Generated by Django 3.1 on 2021-08-31 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20210831_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bik',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)], verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='contact_patronymic',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ-]*$', 'Cпециальные символы не допускаются, за исключением "-"'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(22)], verbose_name='Контактное лицо / Отчество'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ-]*$', 'Cпециальные символы не допускаются, за исключением "-"'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(22)], verbose_name='Контактное лицо / Имя'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='contact_person_surname',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ-]*$', 'Cпециальные символы не допускаются, за исключением "-"'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(22)], verbose_name='Контактное лицо / Фамилия'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='correspondent_account_cb',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(20)], verbose_name='Корреспондентский счет в ЦБ'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='eio_name',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ-]*$', 'Cпециальные символы не допускаются, за исключением "-"'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(22)], verbose_name='ЕИО / Имя'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='eio_patronymic',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ-]*$', 'Cпециальные символы не допускаются, за исключением "-"'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(22)], verbose_name='ЕИО / Отчество'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='eio_surname',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ-]*$', 'Cпециальные символы не допускаются, за исключением "-"'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(22)], verbose_name='ЕИО / Фамилия'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='kpp',
            field=models.CharField(blank=True, max_length=264, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='region',
            field=models.CharField(blank=True, help_text='Пример: 00 - Регион', max_length=264, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='registration_address',
            field=models.CharField(blank=True, help_text='Пример: Индекс Город, Улица, Дом, Помещение', max_length=264, verbose_name='Адрес регистрации'),
        ),
    ]
