# Generated by Django 3.1 on 2021-09-08 13:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20210831_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='bank',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='bankdocument',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='bankdocument',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='bankguarantee',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='bankguaranteestatus',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='bankguaranteestatus',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='banklimits',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='banklimits',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='banktariffmatrix',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='banktariffmatrix',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='bankсontract',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='bankсontract',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='disclosure_conditions',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Условия раскрытия БГ'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='maintain_a_guarantee',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Обязательства по гарантии'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='number',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='rights_and_liabilities_of_the_parties',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Права и обязанности сторон'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма гарантии'),
        ),
        migrations.AlterField(
            model_name='bankguarantee',
            name='termination_of_liabilities',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Прекращение обязательств'),
        ),
    ]
