# Generated by Django 3.1 on 2021-09-10 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_auto_20210910_0739'),
        ('bank', '0016_auto_20210909_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdocument',
            name='document_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bank_document_type', to='order.documenttype', verbose_name='Тип Документа'),
        ),
    ]
