# Generated by Django 3.1 on 2021-09-28 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_auto_20210917_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bik',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)], verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='correspondent_account_cb',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(20)], verbose_name='Корреспондентский счет в ЦБ'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)], verbose_name='КПП'),
        ),
    ]
