# Generated by Django 3.1 on 2021-10-18 11:48

from django.db import migrations, models
import django.db.models.deletion
import garpix_page.utils.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20210930_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('title', models.CharField(default='', max_length=256, verbose_name='Название')),
                ('is_loaded', models.BooleanField(default=False, verbose_name='Загружено?')),
                ('document', models.FileField(default='', upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('title', models.CharField(default='', max_length=256, verbose_name='Название')),
                ('bank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_document', to='bank.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
    ]
