# Generated by Django 3.1 on 2021-10-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_auto_20211018_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='document',
        ),
        migrations.AddField(
            model_name='section',
            name='document',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='section_document', to='bank.Document', verbose_name='Документ'),
        ),
    ]
