# Generated by Django 3.1 on 2021-07-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_portfoliopage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdocumentspage',
            options={'verbose_name': 'Страница "Карточка заявки (документы)"', 'verbose_name_plural': 'Страницы "Карточка заявки (документы)"'},
        ),
        migrations.AlterModelOptions(
            name='orderfinancialreportpage',
            options={'verbose_name': 'Страница "Карточка заявки (финансовая отчетность)"', 'verbose_name_plural': 'Страницы "Карточка заявки (финансовая отчетность)"'},
        ),
        migrations.AlterModelOptions(
            name='orderhistorypage',
            options={'verbose_name': 'Страница "Карточка заявки (история)"', 'verbose_name_plural': 'Страницы "Карточка заявки (история)"'},
        ),
        migrations.AlterModelOptions(
            name='orderlimitpage',
            options={'verbose_name': 'Страница "Карточка заявки (лимит)"', 'verbose_name_plural': 'Страницы "Карточка заявки (лимит)"'},
        ),
        migrations.AlterModelOptions(
            name='orderpurchasepage',
            options={'verbose_name': 'Страница "Карточка заявки (закупка)"', 'verbose_name_plural': 'Страницы "Карточка заявки (закупка)"'},
        ),
        migrations.AlterModelOptions(
            name='orderquotationpage',
            options={'verbose_name': 'Страница "Карточка заявки (котировки)"', 'verbose_name_plural': 'Страницы "Карточка заявки (котировки)"'},
        ),
        migrations.AlterModelOptions(
            name='orderquotationtradepage',
            options={'verbose_name': 'Страница "Карточка заявки (котировки) торг"', 'verbose_name_plural': 'Страницы "Карточка заявки (котировки) торг"'},
        ),
        migrations.AlterModelOptions(
            name='orderratepage',
            options={'verbose_name': 'Страница "Карточка заявки (рейтинг)"', 'verbose_name_plural': 'Страницы "Карточка заявки (рейтинг)"'},
        ),
        migrations.AlterModelOptions(
            name='orderscoringpage',
            options={'verbose_name': 'Страница "Карточка заявки (скоринг)"', 'verbose_name_plural': 'Страницы "Карточка заявки (скоринг)"'},
        ),
        migrations.AlterModelOptions(
            name='orderspage',
            options={'verbose_name': 'Страница "Заявки (список)"', 'verbose_name_plural': 'Страницы "Заявки (список)"'},
        ),
        migrations.AlterModelOptions(
            name='orderstopfactorspage',
            options={'verbose_name': 'Страница "Карточка заявки (стоп-факторы и предсигналы)"', 'verbose_name_plural': 'Страницы "Карточка заявки (стоп-факторы и предсигналы)"'},
        ),
        migrations.AlterModelOptions(
            name='orderunderwritingpage',
            options={'verbose_name': 'Страница "Карточка заявки (андеррайтинг)"', 'verbose_name_plural': 'Страницы "Карточка заявки (андеррайтинг)"'},
        ),
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'verbose_name': 'Страница "Портфель"', 'verbose_name_plural': 'Страницы "Портфель"'},
        ),
    ]
