# Generated by Django 3.1 on 2021-07-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210708_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSpecialCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Специальное условие',
                'verbose_name_plural': 'Специальные условия',
            },
        ),
    ]
