# Generated by Django 3.1 on 2021-08-09 13:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210809_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranty',
            name='provision_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма обеспечения'),
        ),
        migrations.AlterField(
            model_name='guaranty',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма'),
        ),
    ]
