# Generated by Django 3.1 on 2021-08-09 13:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210809_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='purchase_object',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Объект закупки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='contract',
            name='term',
            field=models.DateField(blank=True, null=True, verbose_name='Срок'),
        ),
    ]
