# Generated by Django 3.1 on 2021-08-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210809_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_condition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_condition_orders', to='order.orderspecialcondition', verbose_name='Специальное условие'),
        ),
    ]
