# Generated by Django 3.1 on 2021-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_special_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranty',
            name='fz',
            field=models.CharField(blank=True, max_length=1000, verbose_name='ФЗ'),
        ),
        migrations.AddField(
            model_name='guaranty',
            name='term',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Срок'),
        ),
    ]
