# Generated by Django 3.1 on 2021-08-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210809_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='DataToSignTxtBox',
            field=models.TextField(blank=True, default='', verbose_name='ЭЦП данные'),
        ),
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.TextField(blank=True, default='', verbose_name='ЭЦП'),
        ),
        migrations.AddField(
            model_name='order',
            name='signature_author',
            field=models.TextField(blank=True, default='', verbose_name='ЭЦП Автор'),
        ),
    ]
