# Generated by Django 3.1 on 2021-08-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210812_2202'),
        ('order', '0016_auto_20210812_1909'),
    ]

    operations = [
    ]
