# Generated by Django 3.1 on 2021-08-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_merge_20210816_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingform',
            name='detail_form',
        ),
        migrations.AddField(
            model_name='accountingformdetail',
            name='accounting_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_form', to='order.accountingform', verbose_name='Форма'),
        ),
    ]
