# Generated by Django 3.1 on 2021-08-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_principal_accounting_forms'),
        ('order', '0018_auto_20210816_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingform',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_form', to='entity.principal', verbose_name='Принципал'),
        ),
    ]
