# Generated by Django 3.1 on 2021-08-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_accountingform_principal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='DataToSignTxtBox',
            new_name='data_to_sign_txt_box',
        ),
    ]
