# Generated by Django 3.1 on 2021-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20210816_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingformdetail',
            name='end_value',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Значение на конец периода'),
        ),
        migrations.AlterField(
            model_name='accountingformdetail',
            name='start_value',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Значение на начало периода'),
        ),
    ]
