# Generated by Django 3.1 on 2021-08-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20210816_1316'),
        ('order', '0020_auto_20210816_1330'),
    ]

    operations = [
    ]
