# Generated by Django 3.1 on 2021-08-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_merge_20210816_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
