# Generated by Django 3.1 on 2021-08-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_orderstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статусы заявки'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status', to='order.orderstatus', verbose_name='Статус'),
        ),
    ]
