# Generated by Django 3.1 on 2021-08-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttype',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Название'),
        ),
    ]
