# Generated by Django 3.1 on 2021-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_auto_20210825_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=1000, verbose_name='Номер тогра')),
            ],
            options={
                'verbose_name': 'Тогр',
                'verbose_name_plural': 'Тогри',
            },
        ),
    ]
