# Generated by Django 3.1 on 2021-08-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_auction'),
        ('order', '0027_oliverwymanmodel'),
    ]

    operations = [
    ]
