# Generated by Django 3.1 on 2021-08-25 13:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_auto_20210824_1405'),
        ('order', '0033_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='purchase_object',
        ),
        migrations.AddField(
            model_name='contract',
            name='availability_payment',
            field=models.BooleanField(default=False, verbose_name='Наличие аванса'),
        ),
        migrations.AddField(
            model_name='contract',
            name='availability_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Доля аванса в сумме контракта'),
        ),
        migrations.AddField(
            model_name='contract',
            name='availability_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма аванса'),
        ),
        migrations.AddField(
            model_name='contract',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.beneficiary', verbose_name='Бенефициар'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.contest', verbose_name='Конкурс'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Номер контракта'),
        ),
        migrations.AddField(
            model_name='contract',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.purchase', verbose_name='Закупка'),
        ),
        migrations.AddField(
            model_name='contract',
            name='security_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Размер обеспечения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='treasury_support',
            field=models.BooleanField(default=False, verbose_name='Казначейское сопровождение'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(blank=True, null=True, verbose_name='Срок контракта'),
        ),
    ]
