# Generated by Django 3.1 on 2021-08-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20210826_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Название')),
                ('weight', models.CharField(blank=True, max_length=1000, verbose_name='Вес')),
                ('mark', models.CharField(blank=True, max_length=1000, verbose_name='Балл')),
            ],
            options={
                'verbose_name': 'ФП',
                'verbose_name_plural': 'ФП',
            },
        ),
    ]
