# Generated by Django 3.1 on 2021-08-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_auto_20210826_1232'),
        ('order', '0028_auto_20210826_1215'),
    ]

    operations = [
    ]
