# Generated by Django 3.1 on 2021-08-26 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0008_auto_20210824_1405'),
        ('order', '0040_merge_20210826_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_stop_factors_exists',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_warning_signals_exists',
        ),
        migrations.RemoveField(
            model_name='order',
            name='limit_availability_for_branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='limit_availability_for_fz',
        ),
        migrations.RemoveField(
            model_name='order',
            name='limit_availability_for_region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scoring_ow',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_condition',
        ),
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bank_order', to='bank.bank', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='order',
            name='eis_link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на закупку в ЕИС'),
        ),
        migrations.AddField(
            model_name='order',
            name='pnt',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Реестровый номер торгов'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='order',
            name='underwriter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='underwriter_order', to=settings.AUTH_USER_MODEL, verbose_name='Андеррайтер'),
        ),
        migrations.AlterField(
            model_name='oliverwymanmodel',
            name='courts_4',
            field=models.DecimalField(blank=True, decimal_places=11, default=0.0, max_digits=32, null=True, verbose_name='Общая сумма судов в качестве ответчика за последний год'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='contest_order', to='order.contest', verbose_name='Конкурс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='fp_order', to='order.fp', verbose_name='ФП'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guaranty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='guaranty_order', to='order.guaranty', verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ps',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ps_order', to='order.ps', verbose_name='ПС'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sf',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sf_order', to='order.sf', verbose_name='СФ'),
        ),
    ]
