# Generated by Django 3.1 on 2021-08-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_auto_20210826_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='limit_include',
            field=models.BooleanField(default=False, verbose_name='Учитывать при расчете лимита'),
        ),
    ]
