# Generated by Django 3.1 on 2021-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_orderstatus_limit_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='purchaseNumber',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Номер закупки'),
        ),
    ]
