# Generated by Django 3.1 on 2021-08-31 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_oliverwymanmodel_purchasenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranty',
            name='term',
            field=models.CharField(blank=True, help_text='Пример: 365', max_length=1000, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры')], verbose_name='Срок гарантии(в днях)'),
        ),
    ]
