# Generated by Django 3.1 on 2021-08-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20210831_1240'),
        ('order', '0044_auto_20210831_1224'),
    ]

    operations = [
    ]
