# Generated by Django 3.1 on 2021-09-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_auto_20210909_1551'),
        ('order', '0048_auto_20210908_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranty',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bank_guaranty', to='bank.bank', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='guaranty',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_guaranty', to='bank.bankguaranteestatus', verbose_name='Статус'),
        ),
    ]
