# Generated by Django 3.1 on 2021-09-10 05:07

from django.db import migrations, models
import django.db.models.deletion
import garpix_page.utils.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_auto_20210910_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuarantyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('document', models.FileField(default='', upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='Документ')),
                ('document_title', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Название документа')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guaranty_document_type', to='order.documenttype', verbose_name='Тип документа')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='guaranty_documents', to='order.guaranty', verbose_name='Гарантия')),
            ],
            options={
                'verbose_name': 'Документ гарантии',
                'verbose_name_plural': 'Документы гарантии',
            },
        ),
    ]
