# Generated by Django 3.1 on 2021-09-10 07:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_auto_20210910_0739'),
        ('order', '0052_guarantydocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name': 'Торг', 'verbose_name_plural': 'Торги'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='number',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Номер торга'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('guarantee_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка комиссии по гарантии, % годовых')),
                ('guarantee_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии по гарантии, руб.')),
                ('bank_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка комиссии банка, % годовых')),
                ('bank_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии банка, руб.')),
                ('bank_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Доля в комиссии по гарантии, %')),
                ('insurance_premium_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка страховой премии')),
                ('insurance_premium_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма страховой премии')),
                ('insurance_premium_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Доля в комиссии по гарантии, %')),
                ('master_agent_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка комиссии мастер-агента, % годовых')),
                ('master_agent_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии мастер-агента, руб.')),
                ('master_agent_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Доля в комиссии по гарантии, %')),
                ('agent_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка комиссии агента, % годовых')),
                ('agent_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии агента, руб.')),
                ('agent_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Доля в комиссии по гарантии, %')),
                ('type', models.CharField(choices=[('Авто', 'Авто'), ('Торг', 'Торг'), ('Индивидуальная', 'Индивидуальная')], default=('Авто', 'Авто'), max_length=128, verbose_name='Вид котировки')),
                ('status', models.CharField(choices=[('Первичная', 'Первичная'), ('Торг', 'Торг'), ('Согласована', 'Согласована'), ('Истек срок действия', 'Истек срок действия')], default=('Первичная', 'Первичная'), max_length=128, verbose_name='Статус котировки')),
                ('expiry_date', models.DateField(verbose_name='Действует до')),
                ('auction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_auction', to='order.auction', verbose_name='Торг')),
                ('bank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_bank', to='bank.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Котировка',
                'verbose_name_plural': 'Котировки',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='quote_order', to='order.quote', verbose_name='Котировка'),
        ),
    ]
