# Generated by Django 3.1 on 2021-09-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_auto_20210910_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
    ]
