# Generated by Django 3.1 on 2021-09-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20210913_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guarantydocument',
            old_name='order',
            new_name='guaranty',
        ),
    ]
