# Generated by Django 3.1 on 2021-09-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_orderfactors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfactors',
            options={'verbose_name': 'Фактор заявки', 'verbose_name_plural': 'Факторы заявки'},
        ),
    ]
