# Generated by Django 3.1 on 2021-09-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_auto_20210914_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fp',
            name='types',
        ),
        migrations.RemoveField(
            model_name='ps',
            name='types',
        ),
    ]
