# Generated by Django 3.1 on 2021-09-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_auto_20210914_1404'),
        ('order', '0057_auto_20210914_1439'),
    ]

    operations = [
    ]
