# Generated by Django 3.1 on 2021-09-17 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_auto_20210914_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oliverwymanmodel',
            name='customerInn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12)], verbose_name='ИНН заказчика'),
        ),
        migrations.AlterField(
            model_name='oliverwymanmodel',
            name='supplierInn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12)], verbose_name='ИНН исполнителя'),
        ),
    ]
