# Generated by Django 3.1 on 2021-09-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_auto_20210917_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='catalog',
            field=models.CharField(blank=True, choices=[('STOP', 'STOP'), ('FORCED', 'FORCED'), ('PASSPORT_PRODUCT', 'PASSPORT_PRODUCT')], max_length=255, verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='guarantydocument',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, verbose_name='Валидный'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, verbose_name='Валидный'),
        ),
    ]
