# Generated by Django 3.1 on 2021-09-21 04:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20210920_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='agent_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Доля в комиссии по гарантии, %'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='agent_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка комиссии агента, % годовых'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='agent_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии агента, руб.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='bank_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Доля в комиссии по гарантии, %'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='bank_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка комиссии банка, % годовых'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='bank_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии банка, руб.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='guarantee_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка комиссии по гарантии, % годовых'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='guarantee_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии по гарантии, руб.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='insurance_premium_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Доля в комиссии по гарантии, %'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='insurance_premium_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка страховой премии'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='insurance_premium_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма страховой премии'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='master_agent_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Доля в комиссии по гарантии, %'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='master_agent_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=100, verbose_name='Ставка комиссии мастер-агента, % годовых'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='master_agent_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии мастер-агента, руб.'),
        ),
    ]
