# Generated by Django 3.1 on 2021-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_auto_20210921_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='dumping',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='protocol_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата протокола'),
        ),
    ]
