# Generated by Django 3.1 on 2021-09-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0066_auto_20210921_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='dumping',
            field=models.BooleanField(default=False, verbose_name='Дэмпинг'),
        ),
    ]
