# Generated by Django 3.1 on 2021-09-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_auto_20210922_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='courts_module',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Балл модуля арбитражных судов'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='executory_module',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Балл модуля исполнительных производств'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='finance_module',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Балл финансового модуля'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='pd_pit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Вероятность раскрытия гарантии (в долях)'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='pd_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Вероятность раскрытия гарантии (TTC)'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='qualitative_module',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Балл качественного модуля'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='signals_module',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Балл модуля сигналов'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='tenders_module',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Балл модуля тендеров'),
        ),
    ]
