# Generated by Django 3.1 on 2021-09-26 20:42

from django.db import migrations, models
import django_fsm
import garpix_notify.utils.file


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_auto_20210924_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to=garpix_notify.utils.file.get_file_path, verbose_name='Решение по запросу'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[('CREATED', 'Создана'), ('SENT', 'Отправлена'), ('UNDERWRITING_A_NEW_APPLICATION', 'Андеррайтинг новая заявка'), ('UNDERWRITING_IN_PROGRESS', 'Андеррайтинг в работе'), ('UNDERWRITING_REQUERY', 'Андеррайтинг дозапрос'), ('UNDERWRITING_REFUSAL', 'Андеррайтинг отказ'), ('QUOTE_AUTO', 'Котировка авто'), ('QUOTE_AUCTION', 'Котировка торг'), ('QUOTE_INDIVIDUAL', 'Котировка индивид'), ('QUOTE_SENT', 'Котировка направлена'), ('QUOTE_REDEFINED', 'Котировка переопределена'), ('QUOTE_REFUSAL', 'Котировка отказ'), ('QUOTE_AGREED', 'Котировка согласована'), ('DOCUMENTS_REQUERY', 'Документы дозапрос'), ('DOCUMENTS_SIGNATURE', 'Документы подпись'), ('DOCUMENTS_REFUSAL', 'Документы отказ'), ('WARRANTY_ISSUE_REQUESTED', 'Выпуск гарантии запрошен'), ('GUARANTEE_ISSUED_PAYMENT_EXPECTED', 'Гарантия выпущена ожидается оплата'), ('WARRANTY_DISCLAIMER', 'Выпуск гарантии отказ'), ('WARRANTY_VALID', 'Гарантия действующая'), ('GUARANTEE_BENEFICIARY_CLAIM_RECEIVED', 'Гарантия получено требование бенефицара'), ('GUARANTEE_LATE_PAYMENT_COMMISSION', 'Гарантия просрочка уплаты комиссии'), ('GUARANTEE_PAYMENT_MADE_BENEFICIARY', 'Гарантия произведена выплата бенефициару'), ('GUARANTEE_RECOURSE_CLAIM_MADE_AGAINST_PRINCIPAL', 'Гарантия предъявлено регрессное требование принципалу'), ('GUARANTEE_CLAIM_PAYMENT_INSURANCE_COMPENSATION', 'Гарантия предъявлено требование на выплату страхового возмещения'), ('WARRANTY_EXPIRED', 'Гарантия истек срок действия'), ('GUARANTEE_PAYMENT_INSURANCE_COMPENSATION_MADE', 'Гарантия произведена выплата страхового возмещения'), ('WARRANTY_TERMINATED', 'Гарантия прекращена')], default=('CREATED', 'Создана'), max_length=50),
        ),
    ]
