# Generated by Django 3.1 on 2021-09-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_auto_20210924_1107'),
        ('order', '0072_auto_20210926_2342'),
    ]

    operations = [
    ]
