# Generated by Django 3.1 on 2021-09-28 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0074_auto_20210927_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.purchase', verbose_name='Закупка'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='nmck',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры')], verbose_name='НМЦК'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_object',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Предмет закупки'),
        ),
    ]
