# Generated by Django 3.1 on 2021-09-28 14:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0075_auto_20210928_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='total_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма комиссии по гарантии, руб.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='guarantee_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма гарантии, руб.'),
        ),
    ]
