# Generated by Django 3.1 on 2021-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20210928_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='EBITDA_short_term_debt_cash_and_interest_payments',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Отношение EBITDA к кредиторской задолженности'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='EBITDA_total_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='EBITDA / Общие обязательства'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='capital_assets',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Капитал/Активы'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='dynamics_of_revenue_year_to_year',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Выручка/Выручка(пред. год)'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='instant_liquidity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Мгновенная ликвидность'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='net_profit_cost_of_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Отношение чистой прибыли к стоимости продаж'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='revenues_current_assets',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Отношение выручки к текущим активам'),
        ),
        migrations.AddField(
            model_name='oliverwymanmodel',
            name='total_liabilities_this_year_total_liabilities_previous_year',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Общие обязательства / Общие обязательства (пред. год)'),
        ),
    ]
