# Generated by Django 3.1 on 2021-09-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20210928_1925'),
        ('order', '0075_auto_20210928_1958'),
    ]

    operations = [
    ]
