# Generated by Django 3.1 on 2021-09-30 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_merge_20210929_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oliverwymanmodel',
            name='supplierInn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(10, 'Min value should consist of at least 10 characters'), django.core.validators.MaxLengthValidator(12, 'Max value must not contain more than 12 characters')], verbose_name='ИНН исполнителя'),
        ),
    ]
