# Generated by Django 3.1 on 2021-10-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_auto_20210930_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
