# Generated by Django 3.1 on 2021-10-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0080_quote_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_quotes', to='order.order', verbose_name='Заявка')),
                ('quote', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='quotes', to='order.quote', verbose_name='Котировка')),
            ],
            options={
                'verbose_name': 'Котировка заявки',
                'verbose_name_plural': 'Котировки заявки',
            },
        ),
    ]
