# Generated by Django 3.1 on 2021-10-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0081_orderquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_quote_sent',
            field=models.BooleanField(default=False, verbose_name='Котировка отправлена'),
        ),
    ]
