# Generated by Django 3.1 on 2021-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0083_auto_20211005_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='type',
            field=models.CharField(blank=True, choices=[('REGULATION', 'REGULATION'), ('FINANCIAL', 'FINANCIAL'), ('BUSINESS', 'BUSINESS'), ('OTHER', 'OTHER')], default='Прочие', max_length=100, verbose_name='Тип'),
        ),
    ]
