# Generated by Django 3.1 on 2021-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0084_documenttype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_condition',
            field=models.ManyToManyField(blank=True, related_name='special_condition_order', to='order.OrderSpecialCondition', verbose_name='Специальные условия'),
        ),
    ]
