# Generated by Django 3.1 on 2021-10-11 17:47

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0085_order_special_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[('CREATED', 'Создана'), ('SENT', 'Отправлена'), ('UNDERWRITING_A_NEW_APPLICATION', 'Андеррайтинг новая заявка'), ('UNDERWRITING_IN_PROGRESS', 'Андеррайтинг в работе'), ('UNDERWRITING_REQUERY', 'Андеррайтинг дозапрос'), ('UNDERWRITING_REFUSAL', 'Андеррайтинг отказ'), ('QUOTE_AUTO', 'Котировка авто'), ('QUOTE_AUCTION', 'Котировка торг'), ('QUOTE_INDIVIDUAL', 'Котировка индивид'), ('QUOTE_SENT', 'Котировка направлена'), ('QUOTE_REDEFINED', 'Котировка предоставлена'), ('QUOTE_REFUSAL', 'Котировка отказ'), ('QUOTE_AGREED', 'Котировка согласована'), ('DOCUMENTS_REQUERY', 'Документы дозапрос'), ('DOCUMENTS_SIGNATURE', 'Документы подпись'), ('DOCUMENTS_REFUSAL', 'Документы отказ'), ('GUARANTEE_ISSUE_REQUESTED', 'Выпуск гарантии запрошен'), ('GUARANTEE_ISSUED_PAYMENT_EXPECTED', 'Гарантия выпущена ожидается оплата'), ('GUARANTEE_DISCLAIMER', 'Выпуск гарантии отказ'), ('GUARANTEE_VALID', 'Гарантия действующая'), ('GUARANTEE_BENEFICIARY_CLAIM_RECEIVED', 'Гарантия получено требование бенефицара'), ('GUARANTEE_LATE_PAYMENT_COMMISSION', 'Гарантия просрочка уплаты комиссии'), ('GUARANTEE_PAYMENT_MADE_BENEFICIARY', 'Гарантия произведена выплата бенефициару'), ('GUARANTEE_RECOURSE_CLAIM_MADE_AGAINST_PRINCIPAL', 'Гарантия предъявлено регрессное требование принципалу'), ('GUARANTEE_CLAIM_PAYMENT_INSURANCE_COMPENSATION', 'Гарантия предъявлено требование на выплату страхового возмещения'), ('GUARANTEE_EXPIRED', 'Гарантия истек срок действия'), ('GUARANTEE_PAYMENT_INSURANCE_COMPENSATION_MADE', 'Гарантия произведена выплата страхового возмещения'), ('GUARANTEE_TERMINATED', 'Гарантия прекращена'), ('IN_ARCHIVE', 'Заявки в архиве')], default=('CREATED', 'Создана'), max_length=50),
        ),
    ]
