# Generated by Django 3.1 on 2021-10-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20211011_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Order', 'Order'), ('Guarantee', 'Guarantee')], default='Order', max_length=100, verbose_name='Тип документа'),
        ),
    ]
