# Generated by Django 3.1 on 2021-10-12 20:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0087_order_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='availability_without_acceptance',
            field=models.BooleanField(blank=True, default=False, verbose_name='Наличие права безакцептного списание'),
        ),
        migrations.AddField(
            model_name='order',
            name='provision',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обеспечение'),
        ),
        migrations.AddField(
            model_name='order',
            name='provision_form',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Форма обеспечения'),
        ),
        migrations.AddField(
            model_name='order',
            name='provision_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Сумма обеспечения'),
        ),
        migrations.AddField(
            model_name='order',
            name='security_under_guarantee',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обеспечение по гарантии'),
        ),
        migrations.AddField(
            model_name='order',
            name='take_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения БГ'),
        ),
        migrations.AddField(
            model_name='order',
            name='term',
            field=models.CharField(blank=True, help_text='Пример: 365', max_length=1000, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры')], verbose_name='Срок гарантии(в днях)'),
        ),
    ]
