# Generated by Django 3.1 on 2021-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_auto_20211019_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uw_has_been_changed',
            field=models.BooleanField(default=False, verbose_name='Андеррайтер был переназначен'),
        ),
    ]
