# Generated by Django 3.1 on 2021-10-24 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_order_uw_has_been_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 24, 14, 24, 47, 423498, tzinfo=utc), null=True, verbose_name='Дата начала'),
        ),
    ]
