# Generated by Django 3.1 on 2021-10-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_order_uw_has_been_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Первичная', 'Первичная'), ('Авто', 'Авто'), ('Торг', 'Торг'), ('Индивидуальная', 'Индивидуальная'), ('Согласована', 'Согласована'), ('Истек срок действия', 'Истек срок действия'), ('Отказ', 'Отказ')], default=('Первичная', 'Первичная'), max_length=128, verbose_name='Статус котировки'),
        ),
    ]
