# Generated by Django 3.1 on 2021-10-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_order_uw_has_been_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_state',
            field=models.CharField(blank=True, choices=[('Blank', 'Blank'), ('Something', 'Something'), ('Done', 'Done')], default='Blank', max_length=10),
        ),
    ]
