# Generated by Django 3.1 on 2021-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_order_status_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_retries_count',
            field=models.IntegerField(default=0),
        ),
    ]
