# Generated by Django 3.1 on 2021-10-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_auto_20211024_1601'),
        ('order', '0092_order_status_retries_count'),
        ('order', '0091_auto_20211024_1724'),
    ]

    operations = [
    ]
