# Generated by Django 3.1 on 2021-10-26 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0093_merge_20211024_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.lot', verbose_name='Лот'),
        ),
    ]
