# Generated by Django 3.1 on 2021-11-08 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0094_auto_20211026_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_quote_sent',
        ),
        migrations.AddField(
            model_name='order',
            name='is_quote_agreed',
            field=models.BooleanField(default=False, verbose_name='Котировка согласована'),
        ),
    ]
