from .beneficiary import BeneficiarySerializer
from .principal import PrincipalSerializer
from .principal_financial_indicators import PrincipalFinancialIndicatorsSerializer
from .legal_entity import LegalEntitySerializer
from .person import PersonSerializer, PersonPassportDataSerializer
from .co_owner import CoOwnerSerializer
from .ownership import OwnershipSerializer
