# Generated by Django 3.1 on 2021-07-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitbankpage',
            options={'verbose_name': 'Страница "Лимиты (банк)"', 'verbose_name_plural': 'Страницы "Лимиты (банк)"'},
        ),
        migrations.AlterModelOptions(
            name='limitlistpage',
            options={'verbose_name': 'Страница "Лимиты (список)"', 'verbose_name_plural': 'Страницы "Лимиты (список)"'},
        ),
        migrations.AlterModelOptions(
            name='limitprincipalpage',
            options={'verbose_name': 'Страница "Лимиты (принципал)"', 'verbose_name_plural': 'Страницы "Лимиты (принципал)"'},
        ),
        migrations.AlterModelOptions(
            name='limittypepage',
            options={'verbose_name': 'Страница "Лимиты (вид)"', 'verbose_name_plural': 'Страницы "Лимиты (вид)"'},
        ),
    ]
