# Generated by Django 3.1 on 2021-08-28 09:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('entity', '0016_auto_20210824_1405'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('garpix_menu', '0002_auto_20210705_1805'),
        ('limit', '0003_limitbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitFZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fz', models.CharField(default=None, max_length=32, verbose_name='ФЗ')),
                ('limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Лимит')),
            ],
            options={
                'verbose_name': 'Лимит ФЗ',
                'verbose_name_plural': 'Лимиты ФЗ',
            },
        ),
        migrations.CreateModel(
            name='LimitPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Лимиты"',
                'verbose_name_plural': 'Страницы "Лимиты"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='LimitPrincipalModelPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Страница "Лимиты (принципал)"',
                'verbose_name_plural': 'Страницы "Лимиты (принципал)"',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.RenameModel(
            old_name='LimitPrincipalPage',
            new_name='LimitFZPage',
        ),
        migrations.AlterModelOptions(
            name='limitfzpage',
            options={'verbose_name': 'Страница "Лимиты (ФЗ)"', 'verbose_name_plural': 'Страницы "Лимиты (ФЗ)"'},
        ),
        migrations.CreateModel(
            name='LimitPrincipalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Лимит')),
                ('principal', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='limit_principal', to='entity.principal', verbose_name='Принципал')),
            ],
            options={
                'verbose_name': 'Лимит принципала',
                'verbose_name_plural': 'Лимиты принципалов',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='limits_bank', to='limit.limitbank', verbose_name='Лимит Банка')),
                ('limit_fz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='limits_fz', to='limit.limitfz', verbose_name='Лимит ФЗ')),
                ('limit_principal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='limits_principal', to='limit.limitprincipalmodel', verbose_name='Лимит Принципала')),
                ('principal', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='limits_principal', to='entity.principal', verbose_name='Принципал')),
            ],
            options={
                'verbose_name': 'Лимит',
                'verbose_name_plural': 'Лимиты',
            },
        ),
    ]
