# Generated by Django 3.1 on 2021-09-05 11:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0004_auto_20210828_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='ball_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='Рейтинг в баллах'),
        ),
        migrations.AddField(
            model_name='limit',
            name='letter_rating',
            field=models.CharField(blank=True, choices=[('Рейтинг', (('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D')))], default='', max_length=32, verbose_name='Буквенный рейтинг'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='limit_bank',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='limits_bank', to='limit.limitbank', verbose_name='Лимит Банка'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='limit_fz',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='limits_fz', to='limit.limitfz', verbose_name='Лимит ФЗ'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='limit_principal',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='limits_principal', to='limit.limitprincipalmodel', verbose_name='Лимит Принципала'),
        ),
    ]
