# Generated by Django 3.1 on 2021-09-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0001_initial'),
        ('garpix_menu', '0002_auto_20210705_1805'),
        ('limit', '0007_auto_20210908_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitfzpage',
            name='basepage_ptr',
        ),
        migrations.RemoveField(
            model_name='limitlistpage',
            name='basepage_ptr',
        ),
        migrations.RemoveField(
            model_name='limitpage',
            name='basepage_ptr',
        ),
        migrations.RemoveField(
            model_name='limitprincipalmodelpage',
            name='basepage_ptr',
        ),
        migrations.RemoveField(
            model_name='limittypepage',
            name='basepage_ptr',
        ),
        migrations.DeleteModel(
            name='LimitBankPage',
        ),
        migrations.DeleteModel(
            name='LimitFZPage',
        ),
        migrations.DeleteModel(
            name='LimitListPage',
        ),
        migrations.DeleteModel(
            name='LimitPage',
        ),
        migrations.DeleteModel(
            name='LimitPrincipalModelPage',
        ),
        migrations.DeleteModel(
            name='LimitTypePage',
        ),
    ]
