# Generated by Django 3.1 on 2021-09-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0009_fzlimits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitfz',
            options={'verbose_name': 'ФЗ', 'verbose_name_plural': 'ФЗ'},
        ),
    ]
