# Generated by Django 3.1 on 2021-09-21 13:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0020_auto_20210917_1006'),
        ('limit', '0010_auto_20210920_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitbank',
            options={'verbose_name': 'Установленный лимит банка', 'verbose_name_plural': 'Установленные лимиты банков'},
        ),
        migrations.AlterModelOptions(
            name='limitprincipalmodel',
            options={'verbose_name': 'Установленный лимит принципала', 'verbose_name_plural': 'Установленные лимиты принципалов'},
        ),
        migrations.CreateModel(
            name='PrincipalLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('total_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Установленный лимит')),
                ('current_guaranties_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Действующие БГ')),
                ('orders_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Общая сумма заявок')),
                ('free_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Свободный остаток')),
                ('principal', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='principal_limits', to='entity.principal', verbose_name='Принципал')),
            ],
            options={
                'verbose_name': 'Лимит принципала',
                'verbose_name_plural': 'Лимиты принципала',
            },
        ),
    ]
