# Generated by Django 3.1 on 2021-09-29 14:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0011_auto_20210921_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitprincipalmodel',
            name='current_guaranties_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Действующие БГ'),
        ),
        migrations.AddField(
            model_name='limitprincipalmodel',
            name='free_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Свободный остаток'),
        ),
        migrations.AddField(
            model_name='limitprincipalmodel',
            name='orders_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Общая сумма заявок'),
        ),
        migrations.AddField(
            model_name='limitprincipalmodel',
            name='total_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Установленный лимит'),
        ),
        migrations.DeleteModel(
            name='PrincipalLimits',
        ),
    ]
