# Generated by Django 3.1 on 2021-10-07 13:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0012_auto_20210929_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='financial_indicators',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Финансовые показатели'),
        ),
        migrations.AddField(
            model_name='limit',
            name='ownership_structure',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Структура владения'),
        ),
        migrations.AddField(
            model_name='limit',
            name='score_all_contracts',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Количество исполненных контрактов за последние 3 года'),
        ),
        migrations.AddField(
            model_name='limit',
            name='score_big_contracts',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Количество исполненных за последние 3 года контрактов, стоимостью более либо равной контракту, по которому требуется гарантия'),
        ),
        migrations.AddField(
            model_name='limit',
            name='score_year',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Срок работы Принципала в основном направлении деятельности (лет)'),
        ),
        migrations.AddField(
            model_name='limit',
            name='work_exp',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Опыт работы'),
        ),
    ]
