# Generated by Django 3.1 on 2021-10-12 14:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0013_auto_20211007_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='additional_factors',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Дополнительные факторы'),
        ),
        migrations.AddField(
            model_name='limit',
            name='ball_rating_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='Итоговый рейтинг в баллах'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='ball_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='Расчетный рейтинг в баллах'),
        ),
    ]
