# Generated by Django 3.1 on 2021-10-13 08:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0014_auto_20211012_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='delta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Мнение UW'),
        ),
    ]
