# Generated by Django 3.1 on 2021-10-22 14:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0015_limit_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='add_factor_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Наличие существенной по суммам и/или срокам текущей Картотеки неопл. расчетов'),
        ),
        migrations.AddField(
            model_name='limit',
            name='add_factor_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Наличие существенной по суммам и/или срокам задолженности перед фед. бюдж.'),
        ),
        migrations.AddField(
            model_name='limit',
            name='add_factor_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Наличие просроченной задолженности перед работниками по зараб. плате'),
        ),
        migrations.AddField(
            model_name='limit',
            name='add_factor_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Бюджетные активы, неликвидные запасы на последнюю отчетную дату'),
        ),
        migrations.AddField(
            model_name='limit',
            name='add_factor_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Безнадежная дебиторская задолженность на последнюю отчетную дату'),
        ),
        migrations.AddField(
            model_name='limit',
            name='add_factor_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Наличие текущего убытка с учетом что имеется накопленная прибыль'),
        ),
        migrations.AddField(
            model_name='limit',
            name='add_factor_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Текущий убыток при условии что ЧА положительные'),
        ),
        migrations.AddField(
            model_name='limit',
            name='add_factor_8',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Существенное снижение ЧА'),
        ),
        migrations.AddField(
            model_name='limit',
            name='add_factor_9',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=32, verbose_name='Участие в судебном(ых) процессе(ах)'),
        ),
    ]
